### ISSUE TITLE
infinite loop on ?Mistakes?  ?

### ISSUE THREAD

**Issue by as-muncher** [opentyrian/opentyrian#57]
Hi, I was playing ?Mistakes? and it's in Christmas mode, and I just noticed that the same loop of enemies coming down in a certain way was repeating over and over and over again, the same 3min loop.

**Comment by carlreinke** [comment]
I'm assuming you meant "Mistakes" (without question marks), the secret level in episode 2.  I just played through it in Christmas mode and didn't get stuck in a loop, so I'm going to need more info to reproduce the problem.

**Comment by KScl** [comment]
Mistakes has a lot of loops where if you don't shoot specific enemies the level won't advance, by design.

It also has an errant jump to a location (if I recall correctly, to 9000) that is beyond the level end event, which results in flying through nothingness until the event timer rolls over. This would take patching the level data in some form to fix.

**Comment by as-muncher** [comment]
@carlreinke  I thought that the correctly title was with the question marks at both ends, but maybe that was for another level, not sure.
@KScl  Thanks for the additional information - I thought maybe I was imagining things.

**Comment by as-muncher** [comment]
Ok, so it's ?TUNNEL? that has the question marks on both sides.  Maybe it's also ?MISTAKES? but I'm not sure.    as of 2.1.20130907 anyways.
